/*
 * Static page CSS (add to globals.css):
 *
 * .static-page { max-width: 720px; margin: 0 auto; }
 * .static-page h1 { font-family: var(--mono); font-size: 28px; font-weight: 700; letter-spacing: -0.5px; margin-bottom: 8px; }
 * .static-page .subtitle { font-size: 14px; color: var(--text-dim); margin-bottom: 32px; }
 * .static-page h2 { font-family: var(--mono); font-size: 15px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; color: var(--lime); margin-top: 40px; margin-bottom: 12px; }
 * .static-page p { font-size: 15px; line-height: 1.7; color: var(--text-dim); margin-bottom: 16px; }
 * .static-page a { color: var(--lime); text-decoration: underline; text-underline-offset: 3px; }
 * .static-page a:hover { color: var(--text); }
 * .static-page ul { list-style: none; padding: 0; margin-bottom: 16px; }
 * .static-page ul li { padding: 4px 0; font-size: 14px; color: var(--text-dim); }
 * .static-page ul li::before { content: '\2022'; color: var(--text-faint); margin-right: 10px; }
 * .static-page .divider { border: none; border-top: 1px solid var(--border); margin: 32px 0; }
 */

import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'About',
  description:
    'pill.finance is an AI-powered market intelligence lab delivering twice-daily briefings across 19 assets. Founded by Selim Onay.',
};

export default function AboutPage() {
  return (
    <div className="static-page">
      <h1>About pill.finance</h1>
      <p className="subtitle">AI-powered market intelligence, twice daily.</p>

      <h2>What We Do</h2>
      <p>
        pill.finance is a market intelligence lab that delivers concise,
        actionable briefings for 19 assets across FX, commodities, indices,
        crypto, and stocks. Every weekday at 06:30 and 19:00 TRT, our system
        distils what happened, why it matters, and what to watch into a format
        you can absorb in minutes.
      </p>

      <h2>Who Is Behind It</h2>
      <p>
        pill.finance was founded by{' '}
        <Link href="/author/selim-onay">Selim Onay</Link>, a forex broker
        operations expert and co-founder of FXHelpDesk. With deep experience in
        the brokerage industry and market microstructure, Selim built
        pill.finance to bridge the gap between raw market data and the
        intelligence traders actually need.
      </p>

      <h2>Our Approach</h2>
      <p>
        We combine AI-driven analysis with human-curated asset selection. Every
        briefing follows our Past / Why / Watch framework: what moved, the
        drivers behind it, and the levels and events that matter next. The asset
        list is hand-picked by domain experts; the analysis is generated by
        purpose-built AI systems trained on financial data.
      </p>

      <hr className="divider" />

      <p>
        Questions?{' '}
        <Link href="/contact">Get in touch</Link> or read{' '}
        <Link href="/how-it-works">how it works</Link>.
      </p>
    </div>
  );
}
