import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Terms of service for pill.finance. Informational purposes only, not financial advice.',
};

export default function TermsPage() {
  return (
    <div className="static-page">
      <h1>Terms of Service</h1>
      <p className="subtitle">Last updated: 10 May 2026</p>

      <h2>Not Financial Advice</h2>
      <p>
        pill.finance provides market commentary and analysis for informational
        and educational purposes only. Nothing on this site constitutes
        financial advice, investment advice, trading advice, or any other form
        of professional advice. You should not treat any content on pill.finance
        as a recommendation to buy, sell, or hold any financial instrument.
      </p>

      <h2>No Guarantees of Accuracy</h2>
      <p>
        While we strive for accuracy, pill.finance makes no warranties or
        representations regarding the completeness, accuracy, reliability, or
        timeliness of the information provided. Market data, prices, and
        analysis may contain errors or be delayed. Always verify information
        independently before making financial decisions.
      </p>

      <h2>AI-Generated Content</h2>
      <p>
        Briefings on pill.finance are generated by AI systems. AI-generated
        content may contain inaccuracies, misinterpretations, or outdated
        information. Users should exercise their own judgment and consult
        qualified financial professionals before acting on any information
        presented.
      </p>

      <h2>Risk Disclosure</h2>
      <p>
        Trading and investing in financial markets carries significant risk.
        You can lose some or all of your invested capital. Past performance is
        not indicative of future results. pill.finance is not responsible for
        any losses incurred as a result of using information from this site.
      </p>

      <h2>Intellectual Property</h2>
      <p>
        All content on pill.finance, including text, data, design, and code, is
        the property of pill.finance and its creators. You may not reproduce,
        distribute, or create derivative works from this content without prior
        written permission.
      </p>

      <h2>Use of the Site</h2>
      <p>
        By accessing pill.finance, you agree to use the site for lawful
        purposes only. You agree not to scrape, crawl, or otherwise
        programmatically access the site beyond the provided API and RSS feed
        without permission.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, pill.finance and its creators
        shall not be liable for any direct, indirect, incidental, consequential,
        or special damages arising from your use of the site or reliance on its
        content.
      </p>

      <h2>Changes</h2>
      <p>
        We reserve the right to modify these terms at any time. Continued use
        of the site after changes constitutes acceptance of the updated terms.
      </p>
    </div>
  );
}
